// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Northwind
{
	[Alias("Employees")]
    public partial class EmployeeEntity : IHasId<int> 
    {
        [Alias("Employee ID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Alias("Last Name")]
        [Required]
        public string LastName { get; set;}
        [Alias("First Name")]
        [Required]
        public string FirstName { get; set;}
        public string Title { get; set;}
        [Alias("Birth Date")]
        public DateTime? BirthDate { get; set;}
        [Alias("Hire Date")]
        public DateTime? HireDate { get; set;}
        public string Address { get; set;}
        public string City { get; set;}
        public string Region { get; set;}
        [Alias("Postal Code")]
        public string PostalCode { get; set;}
        public string Country { get; set;}
        [Alias("Home Phone")]
        public string HomePhone { get; set;}
        public string Extension { get; set;}
        public byte[] Photo { get; set;}
        public string Notes { get; set;}
        [Alias("Reports To")]
        public int? ReportsTo { get; set;}
    }
}
#pragma warning restore 1591
