// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Northwind.Data.Model
{
	[Alias("Order Details")]
    public partial class OrderDetailEntity : IEntity 
    {
        [Alias("Order ID")]
        [Required]
        public int OrderID { get; set;}
        [Alias("Product ID")]
        [Required]
        public int ProductID { get; set;}
        [Alias("Unit Price")]
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public short Quantity { get; set;}
        [Required]
        public float Discount { get; set;}
    }
}
#pragma warning restore 1591
