// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Northwind
{
	[Alias("Orders")]
    public partial class OrderEntity : IHasId<int> 
    {
        [Alias("Order ID")]
        [Required]
        public int Id { get; set;}
        [Alias("Customer ID")]
        [Required]
        public string CustomerID { get; set;}
        [Alias("Employee ID")]
        public int? EmployeeID { get; set;}
        [Alias("Ship Name")]
        public string ShipName { get; set;}
        [Alias("Ship Address")]
        public string ShipAddress { get; set;}
        [Alias("Ship City")]
        public string ShipCity { get; set;}
        [Alias("Ship Region")]
        public string ShipRegion { get; set;}
        [Alias("Ship Postal Code")]
        public string ShipPostalCode { get; set;}
        [Alias("Ship Country")]
        public string ShipCountry { get; set;}
        [Alias("Ship Via")]
        public int? ShipVia { get; set;}
        [Alias("Order Date")]
        public DateTime? OrderDate { get; set;}
        [Alias("Required Date")]
        public DateTime? RequiredDate { get; set;}
        [Alias("Shipped Date")]
        public DateTime? ShippedDate { get; set;}
        public decimal? Freight { get; set;}
    }
}
#pragma warning restore 1591
