 
 
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Northwind.SQLite`
//     Provider:               `System.Data.SQLite`
//     Connection String:      `Data Source=Northwind.sqlite;Foreign Keys=True`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SQLiteFactory`
