// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Northwind
{
	[Alias("Suppliers")]
    public partial class SupplierEntity : IHasId<int> 
    {
        [Alias("Supplier ID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Alias("Company Name")]
        [Required]
        public string CompanyName { get; set;}
        [Alias("Contact Name")]
        public string ContactName { get; set;}
        [Alias("Contact Title")]
        public string ContactTitle { get; set;}
        public string Address { get; set;}
        public string City { get; set;}
        public string Region { get; set;}
        [Alias("Postal Code")]
        public string PostalCode { get; set;}
        public string Country { get; set;}
        public string Phone { get; set;}
        public string Fax { get; set;}
    }
}
#pragma warning restore 1591
