// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Northwind.Data.Model
{
	[Alias("Suppliers")]
    public partial class SupplierEntity : IEntity, IHasId<long> 
    {
        [Alias("Id")]
        [Required]
        public long Id { get; set;}
        [StringLength(8000)]
        public string CompanyName { get; set;}
        [StringLength(8000)]
        public string ContactName { get; set;}
        [StringLength(8000)]
        public string ContactTitle { get; set;}
        [StringLength(8000)]
        public string Address { get; set;}
        [StringLength(8000)]
        public string City { get; set;}
        [StringLength(8000)]
        public string Region { get; set;}
        [StringLength(8000)]
        public string PostalCode { get; set;}
        [StringLength(8000)]
        public string Country { get; set;}
        [StringLength(8000)]
        public string Phone { get; set;}
        [StringLength(8000)]
        public string Fax { get; set;}
        [StringLength(8000)]
        public string HomePage { get; set;}
    }
}
#pragma warning restore 1591
